[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlmodel",
    "openai",
    "python-dotenv",
    "pydantic",
    "bcrypt",
    "python-multipart",
    "python-jose[cryptography]",
    "psycopg2-binary",
    "pgvector",
    "alembic"
]


