# Database layer: RDS PostgreSQL with pgvector, plus the two sets of credentials
# the two-role model needs.
#
# Why two roles (scripts/bootstrap_db.sql, docs/architecture/security.md 7.3):
#
#   coursellm_owner  the RDS master user, owns the schema, runs migrations and
#                    scripts/bootstrap_db.sql. It is a member of rds_superuser
#                    so it can CREATE EXTENSION vector, and it is the role that
#                    connects when Alembic runs as the one-off ECS task.
#   coursellm_app    created by bootstrap_db.sql with NOSUPERUSER NOBYPASSRLS.
#                    The API service connects as this role, which is what makes
#                    FORCE ROW LEVEL SECURITY actually apply to it instead of
#                    being assumed. A superuser or a BYPASSRLS role would read
#                    every tenant's rows and the isolation tests would pass for
#                    the wrong reason.
#
# The master password is generated by Terraform (random_password), never typed
# into a file, and written to Secrets Manager. It therefore exists in Terraform
# state: the state must be a remote, encrypted backend that is never committed.
# `environments/*/backend.tf` carries the commented backend block that does that.
#
# Nothing is applied. `terraform plan` is the only command intended here.

locals {
  name_prefix = "${var.project}-${var.environment}"

  # The scheme is a separate format argument on purpose: a literal
  # scheme-then-user-then-password URL shape in a tracked file trips the
  # repository secret scanner (scripts/scan_secrets.sh), which cannot tell a
  # format string from a credential. Splitting the scheme keeps the scanner
  # meaningful.
  #
  # libpq form for psql(1), used by the one-off migration task.
  owner_database_url = format(
    "%s://%s:%s@%s:%d/%s?sslmode=require",
    "postgresql",
    var.master_username,
    urlencode(random_password.master.result),
    aws_db_instance.this.address,
    aws_db_instance.this.port,
    var.db_name,
  )

  # SQLAlchemy/asyncpg form for the application task.
  app_database_url = format(
    "%s://%s:%s@%s:%d/%s?ssl=require",
    "postgresql+asyncpg",
    var.app_role_name,
    urlencode(random_password.app.result),
    aws_db_instance.this.address,
    aws_db_instance.this.port,
    var.db_name,
  )
}

# No special characters in either password: the value is embedded in a URL and
# passed through psql, and 32 alphanumerics is already far beyond brute force.
resource "random_password" "master" {
  length  = 32
  special = false
}

resource "random_password" "app" {
  length  = 32
  special = false
}

resource "aws_db_subnet_group" "this" {
  name        = "${local.name_prefix}-db-subnets"
  description = "Private subnets for ${local.name_prefix} RDS"
  subnet_ids  = var.private_subnet_ids

  tags = merge(var.tags, { Name = "${local.name_prefix}-db-subnets" })
}

# A custom parameter group, not the default, so that TLS can be enforced.
# pgvector needs no shared_preload_libraries entry: it is CREATE EXTENSION-able
# on the stock postgres16 family, which is why force_ssl is the only setting
# that must be pinned here.
resource "aws_db_parameter_group" "this" {
  name        = "${local.name_prefix}-pg-params"
  family      = var.parameter_group_family
  description = "${local.name_prefix} PostgreSQL parameters"

  parameter {
    name  = "rds.force_ssl"
    value = "1"
    # Requires a reboot to take effect on an existing instance; a fresh instance
    # starts with it applied.
    apply_method = "pending-reboot"
  }

  parameter {
    name  = "log_min_duration_statement"
    value = "1000"
  }

  tags = merge(var.tags, { Name = "${local.name_prefix}-pg-params" })
}

resource "aws_db_instance" "this" {
  identifier = "${local.name_prefix}-pg"

  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  db_name  = var.db_name
  username = var.master_username
  password = random_password.master.result
  port     = 5432

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = var.storage_type
  storage_encrypted     = true
  kms_key_id            = var.kms_key_arn == "" ? null : var.kms_key_arn

  multi_az = var.multi_az

  # Private-only. There is no public path to the data tier; the security group
  # is the second lock on the same door.
  publicly_accessible    = false
  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = var.security_group_ids
  parameter_group_name   = aws_db_parameter_group.this.name

  backup_retention_period    = var.backup_retention_period
  backup_window              = var.backup_window
  maintenance_window         = var.maintenance_window
  copy_tags_to_snapshot      = true
  auto_minor_version_upgrade = var.auto_minor_version_upgrade

  performance_insights_enabled          = var.performance_insights_enabled
  performance_insights_retention_period = var.performance_insights_enabled ? var.performance_insights_retention_period : null

  enabled_cloudwatch_logs_exports = var.enabled_cloudwatch_logs_exports

  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : var.final_snapshot_identifier

  # A plan must never mutate a running database as a side effect of being read.
  apply_immediately = false

  tags = merge(var.tags, { Name = "${local.name_prefix}-pg" })
}

# --- credentials -------------------------------------------------------------

resource "aws_secretsmanager_secret" "master" {
  name        = "${local.name_prefix}/rds/master"
  description = "RDS master (schema owner) credentials for ${local.name_prefix}. Rotate by updating the secret and a new task revision; see README."
  kms_key_id  = var.kms_key_arn == "" ? null : var.kms_key_arn

  recovery_window_in_days = var.secret_recovery_window_days

  tags = merge(var.tags, { Name = "${local.name_prefix}/rds/master" })
}

resource "aws_secretsmanager_secret_version" "master" {
  secret_id = aws_secretsmanager_secret.master.id

  secret_string = jsonencode({
    username           = var.master_username
    password           = random_password.master.result
    engine             = "postgres"
    host               = aws_db_instance.this.address
    port               = aws_db_instance.this.port
    dbname             = var.db_name
    OWNER_DATABASE_URL = local.owner_database_url
  })
}

resource "aws_secretsmanager_secret" "app" {
  name        = "${local.name_prefix}/rds/app"
  description = "Application role (${var.app_role_name}, NOSUPERUSER NOBYPASSRLS) credentials and the assembled DATABASE_URL for ${local.name_prefix}."
  kms_key_id  = var.kms_key_arn == "" ? null : var.kms_key_arn

  recovery_window_in_days = var.secret_recovery_window_days

  tags = merge(var.tags, { Name = "${local.name_prefix}/rds/app" })
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id = aws_secretsmanager_secret.app.id

  secret_string = jsonencode({
    username      = var.app_role_name
    password      = random_password.app.result
    engine        = "postgres"
    host          = aws_db_instance.this.address
    port          = aws_db_instance.this.port
    dbname        = var.db_name
    DATABASE_URL  = local.app_database_url
    APP_ROLE_NAME = var.app_role_name
  })
}
