# Remote state for the prod environment.
#
# This is a separate root module from dev with a separate state key, and it must
# never share a state file with dev: one state for both environments means a
# plan against dev can propose changes to production resources.
#
# The backend block is commented out on purpose so a reviewer can run
# `terraform init -backend=false && terraform validate` with no bucket and no
# credentials. To switch to remote state:
#
#   1. Create a versioned, encrypted, private state bucket and a lock table (see
#      ../dev/backend.tf for the exact commands; use a separate bucket or at
#      least a separate key for prod, and consider a separate account).
#
#   2. Uncomment the block below and set the bucket and table names.
#
#   3. `terraform init -migrate-state` and confirm.
#
# The RDS master password and the application-role password are generated by
# Terraform and stored in Secrets Manager, so their values exist in Terraform
# state. That makes the state file a credential-bearing artefact: remote,
# encrypted, versioned, access-restricted, and never committed. `*.tfstate` is
# gitignored.

# terraform {
#   backend "s3" {
#     bucket         = "coursellm-tfstate-prod-REPLACE_WITH_ACCOUNT_ID"
#     key            = "coursellm/prod/terraform.tfstate"
#     region         = "us-east-1"
#     dynamodb_table = "coursellm-tf-lock-prod"
#     encrypt        = true
#   }
# }
