"""Add chunk_index and update vector size

Revision ID: 9fc059ca10c7
Revises: ccce5b135512
Create Date: 2026-05-20 02:00:47.974086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9fc059ca10c7'
down_revision: Union[str, Sequence[str], None] = 'ccce5b135512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chunks_chunk_index'), 'chunks', ['chunk_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_chunk_index'), table_name='chunks')
    op.drop_column('chunks', 'chunk_index')
    # ### end Alembic commands ###
