"""Add background generation tables

Revision ID: 2af17b1a0578
Revises: 8fe7466e87d9
Create Date: 2026-05-23 17:18:28.988865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '2af17b1a0578'
down_revision: Union[str, Sequence[str], None] = '8fe7466e87d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic_order', sa.Integer(), nullable=False),
    sa.Column('chunk_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_topics_document_id'), 'document_topics', ['document_id'], unique=False)
    op.create_table('generated_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('formulas', sa.JSON(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_notes_document_id'), 'generated_notes', ['document_id'], unique=False)
    op.create_table('generation_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('depends_on', sa.Uuid(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_status_document_id'), 'generation_status', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_status_document_id'), table_name='generation_status')
    op.drop_table('generation_status')
    op.drop_index(op.f('ix_generated_notes_document_id'), table_name='generated_notes')
    op.drop_table('generated_notes')
    op.drop_index(op.f('ix_document_topics_document_id'), table_name='document_topics')
    op.drop_table('document_topics')
    # ### end Alembic commands ###
