"""add_planner_tables

Revision ID: a2b5e028ce8e
Revises: ac1a9da9d536
Create Date: 2026-05-26 21:43:03.956949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a2b5e028ce8e'
down_revision: Union[str, Sequence[str], None] = 'ac1a9da9d536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_type', sa.Enum('ASSIGNMENT', 'EXAM', 'LECTURE', 'REVIEW', 'DEADLINE', 'MEETING', name='eventtype'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('source_email_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planner_events_user_id'), 'planner_events', ['user_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_user_id'), 'study_plans', ['user_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('reminder_time', sa.DateTime(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['planner_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    op.drop_index(op.f('ix_study_plans_user_id'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_planner_events_user_id'), table_name='planner_events')
    op.drop_table('planner_events')
    # ### end Alembic commands ###
