"""Assessment use cases: generate, read, answer, and read progress.

This is the only layer that knows how a generated draft becomes a row, and it is
where the invariants that span several tables are enforced:

* **A quiz is persisted before it is returned.** ``GET /api/v1/quizzes/{id}``
  must be able to serve a draft generated by an earlier request, so generation
  and persistence are one use case.
* **Cross-tenant and cross-user are both 404.** A quiz or attempt belonging to
  another tenant — or to another user in the same tenant — is indistinguishable
  from one that does not exist.
* **One evaluation writes exactly one event.** The event log is append-only and
  the mastery projection is derived from it, so the write happens here and the
  projection itself is never stored. The read side is delegated to
  :class:`~coursellm.services.roadmap.RoadmapService`, which already composes the
  projection, weak/stale concepts, velocity and the next action.
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from dataclasses import dataclass
from typing import cast

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from coursellm.assessment.evaluator import evaluate_answer
from coursellm.assessment.generator import generate_quiz
from coursellm.assessment.schemas import (
    AssessmentResult,
    Difficulty,
    ItemType,
    QuizCitation,
    QuizDraft,
    QuizItem,
)
from coursellm.core.config import Settings
from coursellm.core.errors import NotFoundError
from coursellm.db.models.assessment import Quiz
from coursellm.db.models.learning import QuizAttempt
from coursellm.db.tenancy import TenantScope
from coursellm.llm import LLMGateway
from coursellm.services.roadmap import ProgressOverview, RoadmapService

#: Default number of attempts returned by the paginated history route.
DEFAULT_ATTEMPT_LIMIT = 20
#: Number of recent attempts embedded in the progress summary.
RECENT_ATTEMPT_LIMIT = 5


@dataclass(frozen=True, slots=True)
class AttemptPage:
    """One page of the caller's attempt history."""

    attempts: tuple[QuizAttempt, ...]
    total: int
    limit: int
    offset: int


class AssessmentService:
    """Use cases over quiz drafts, attempts and the progress read model."""

    def __init__(self, session: AsyncSession, scope: TenantScope) -> None:
        self._session = session
        self._scope = scope

    @property
    def tenant_id(self) -> uuid.UUID:
        return self._scope.tenant_id

    # -- quiz drafts ------------------------------------------------------
    async def generate(
        self,
        *,
        user_id: uuid.UUID,
        settings: Settings,
        gateway: LLMGateway,
        course_id: uuid.UUID,
        concept_ids: Sequence[uuid.UUID] | None = None,
        n_items: int = 5,
        difficulty: Difficulty | None = None,
        item_types: Sequence[ItemType] | None = None,
    ) -> QuizDraft:
        """Generate a grounded draft and persist it, returning it with its id."""
        draft = await generate_quiz(
            self._session,
            self._scope,
            settings,
            gateway,
            user_id=user_id,
            course_id=course_id,
            concept_ids=concept_ids,
            n_items=n_items,
            difficulty=difficulty,
            item_types=item_types,
        )
        quiz = Quiz(
            tenant_id=self.tenant_id,
            user_id=user_id,
            course_id=course_id,
            difficulty=draft.difficulty,
            n_items=draft.requested_items,
            shortfall=draft.shortfall,
            concept_ids=[str(concept_id) for concept_id in draft.concept_ids],
            item_types=list(draft.item_types),
            items=[item.model_dump(mode="json") for item in draft.items],
            citations=[citation.model_dump(mode="json") for citation in draft.citations],
            degraded=list(draft.degraded),
        )
        self._session.add(quiz)
        await self._session.flush()
        draft.quiz_id = quiz.id
        draft.course_id = course_id
        return draft

    async def get_quiz(self, *, quiz_id: uuid.UUID, user_id: uuid.UUID) -> QuizDraft:
        return _draft_from_row(await self._get_owned_quiz(quiz_id, user_id))

    # -- answers ----------------------------------------------------------
    async def submit_answer(
        self,
        *,
        quiz_id: uuid.UUID,
        item_id: str,
        answer: str,
        user_id: uuid.UUID,
        settings: Settings,
        gateway: LLMGateway,
    ) -> AssessmentResult:
        """Create an attempt for one item and evaluate it.

        The placeholder attempt is created first so the event and the grade share
        one transaction; the evaluator removes it again if scoring fails, so a
        failed evaluation cannot project as a recorded zero.
        """
        quiz = await self._get_owned_quiz(quiz_id, user_id)
        item = _find_item(quiz, item_id)
        if item is None:
            msg = "Quiz item not found."
            raise NotFoundError(msg)

        attempt = QuizAttempt(
            tenant_id=self.tenant_id,
            user_id=user_id,
            course_id=quiz.course_id,
            quiz_id=quiz.id,
            item_id=item_id,
            concept_ids=[] if item.concept_id is None else [str(item.concept_id)],
            answer=answer,
        )
        self._session.add(attempt)
        await self._session.flush()
        return await evaluate_answer(
            self._session,
            self._scope,
            settings,
            gateway,
            user_id=user_id,
            quiz_attempt_id=attempt.id,
            item_id=item_id,
            answer=answer,
        )

    async def evaluate_existing_attempt(
        self,
        *,
        attempt_id: uuid.UUID,
        item_id: str,
        answer: str,
        user_id: uuid.UUID,
        settings: Settings,
        gateway: LLMGateway,
    ) -> AssessmentResult:
        """Score an attempt that already exists (the ``evaluate_answer`` tool path)."""
        return await evaluate_answer(
            self._session,
            self._scope,
            settings,
            gateway,
            user_id=user_id,
            quiz_attempt_id=attempt_id,
            item_id=item_id,
            answer=answer,
        )

    # -- progress reads ---------------------------------------------------
    async def progress_summary(
        self, *, user_id: uuid.UUID, course_id: uuid.UUID | None = None
    ) -> ProgressOverview:
        """The projected progress overview, composed by the roadmap service.

        The projection is not recomputed here and never in a router: the read
        model has exactly one implementation, in ``learning/progress.py``,
        reached through the service that already owns it.
        """
        return await RoadmapService(self._session, self._scope).progress_overview(
            user_id=user_id, course_id=course_id
        )

    async def recent_attempts(
        self, *, user_id: uuid.UUID, limit: int = RECENT_ATTEMPT_LIMIT
    ) -> list[QuizAttempt]:
        stmt = (
            select(QuizAttempt)
            .where(
                QuizAttempt.tenant_id == self.tenant_id,
                QuizAttempt.user_id == user_id,
            )
            .order_by(QuizAttempt.created_at.desc(), QuizAttempt.id.desc())
            .limit(limit)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def attempt_page(
        self, *, user_id: uuid.UUID, limit: int = DEFAULT_ATTEMPT_LIMIT, offset: int = 0
    ) -> AttemptPage:
        base = (
            QuizAttempt.tenant_id == self.tenant_id,
            QuizAttempt.user_id == user_id,
        )
        total = int(
            (
                await self._session.execute(
                    select(func.count()).select_from(QuizAttempt).where(*base)
                )
            ).scalar_one()
        )
        stmt = (
            select(QuizAttempt)
            .where(*base)
            .order_by(QuizAttempt.created_at.desc(), QuizAttempt.id.desc())
            .limit(limit)
            .offset(offset)
        )
        attempts = tuple((await self._session.execute(stmt)).scalars().all())
        return AttemptPage(attempts=attempts, total=total, limit=limit, offset=offset)

    # -- internals --------------------------------------------------------
    async def _get_owned_quiz(self, quiz_id: uuid.UUID, user_id: uuid.UUID) -> Quiz:
        stmt = select(Quiz).where(
            Quiz.tenant_id == self.tenant_id,
            Quiz.id == quiz_id,
            Quiz.user_id == user_id,
        )
        quiz = (await self._session.execute(stmt)).scalar_one_or_none()
        if quiz is None:
            msg = "Quiz not found."
            raise NotFoundError(msg)
        return quiz


def _draft_from_row(quiz: Quiz) -> QuizDraft:
    return QuizDraft(
        quiz_id=quiz.id,
        course_id=quiz.course_id,
        concept_ids=[uuid.UUID(str(value)) for value in quiz.concept_ids or []],
        difficulty=_as_difficulty(quiz.difficulty),
        item_types=_as_item_types(quiz.item_types or []),
        items=[QuizItem.model_validate(raw) for raw in quiz.items or []],
        citations=[QuizCitation.model_validate(raw) for raw in quiz.citations or []],
        requested_items=quiz.n_items,
        shortfall=quiz.shortfall,
        degraded=list(quiz.degraded or []),
    )


def _find_item(quiz: Quiz, item_id: str) -> QuizItem | None:
    for item in _draft_from_row(quiz).items:
        if item.item_id == item_id:
            return item
    return None


def _as_difficulty(value: str) -> Difficulty:
    if value in ("easy", "hard"):
        return cast("Difficulty", value)
    return "medium"


def _as_item_types(values: Sequence[str]) -> list[ItemType]:
    allowed: list[ItemType] = []
    for value in values:
        if value in ("multiple_choice", "short_answer", "concept_check"):
            allowed.append(cast("ItemType", value))
    return allowed


__all__ = [
    "DEFAULT_ATTEMPT_LIMIT",
    "RECENT_ATTEMPT_LIMIT",
    "AssessmentService",
    "AttemptPage",
]
