"""add llm usage

Adds the per-attempt model accounting table, then applies the two things
autogenerate cannot express: Row-Level Security on the new table, keyed on the
``app.tenant_id`` session variable.

The table list is duplicated from ``coursellm.db.base.TENANT_SCOPED_TABLES`` on
purpose, exactly as in the initial migration: a migration must describe the
schema as it was at this revision, and importing application code would make an
old migration change meaning when the code does.

Revision ID: 5b9bac36ed61
Revises: 9540db2f8c9a
Create Date: 2026-09-25 01:24:18.877807
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5b9bac36ed61"
down_revision: str | None = "9540db2f8c9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Only the table added by this revision. The security test unions this list
# with the one in the initial migration and compares it to the code's list.
TENANT_SCOPED_TABLES = ("llm_usage",)

TENANT_GUC = "app.tenant_id"


def _enable_rls() -> None:
    """Turn on Row-Level Security and add the isolation policy.

    The ``NULLIF(..., '')`` wrapper is required for the same reason as in the
    initial migration: PostgreSQL resets a transaction-local custom setting to
    the empty string on commit, so a bare cast raises ``invalid input syntax for
    type uuid: ""`` on the next unscoped query served by a pooled connection.

    ``FORCE ROW LEVEL SECURITY`` makes the policy apply to the table owner too;
    without it a single-role deployment would silently bypass every policy.
    """
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
                USING (tenant_id = NULLIF(current_setting('{TENANT_GUC}', true), '')::uuid)
                WITH CHECK (tenant_id = NULLIF(current_setting('{TENANT_GUC}', true), '')::uuid)
            """
        )


def _disable_rls() -> None:
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_usage",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("request_id", sa.UUID(), nullable=True),
        sa.Column(
            "task",
            sa.Enum(
                "classification",
                "extraction",
                "tutoring",
                "reasoning",
                name="modeltask",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("purpose", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("used_fallback", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=12, scale=6), server_default="0", nullable=False
        ),
        sa.Column("priced", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="1", nullable=False),
        sa.Column("error_type", sa.String(length=80), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_llm_usage_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_llm_usage_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_usage")),
    )
    op.create_index(op.f("ix_llm_usage_request_id"), "llm_usage", ["request_id"], unique=False)
    op.create_index(
        "ix_llm_usage_tenant_created_at", "llm_usage", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_llm_usage_tenant_id"), "llm_usage", ["tenant_id"], unique=False)
    op.create_index("ix_llm_usage_tenant_model", "llm_usage", ["tenant_id", "model"], unique=False)
    op.create_index(
        "ix_llm_usage_tenant_request", "llm_usage", ["tenant_id", "request_id"], unique=False
    )
    # ### end Alembic commands ###

    _enable_rls()


def downgrade() -> None:
    _disable_rls()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_llm_usage_tenant_request", table_name="llm_usage")
    op.drop_index("ix_llm_usage_tenant_model", table_name="llm_usage")
    op.drop_index(op.f("ix_llm_usage_tenant_id"), table_name="llm_usage")
    op.drop_index("ix_llm_usage_tenant_created_at", table_name="llm_usage")
    op.drop_index(op.f("ix_llm_usage_request_id"), table_name="llm_usage")
    op.drop_table("llm_usage")
    # ### end Alembic commands ###
