# Remote state for the dev environment.
#
# The backend block is commented out on purpose. A reviewer validating this
# configuration runs
#
#     terraform init -backend=false
#     terraform validate
#
# from this directory, which needs no bucket and no credentials. Switching to
# remote state is a deliberate, one-time bootstrap:
#
#   1. Create the state bucket and lock table in the account that owns dev:
#
#        aws s3api create-bucket \
#          --bucket coursellm-tfstate-<account-id> \
#          --region us-east-1
#        aws s3api put-bucket-versioning \
#          --bucket coursellm-tfstate-<account-id> \
#          --versioning-configuration Status=Enabled
#        aws s3api put-bucket-encryption \
#          --bucket coursellm-tfstate-<account-id> \
#          --server-side-encryption-configuration \
#          '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"aws:kms"}}]}'
#        aws s3api put-public-access-block \
#          --bucket coursellm-tfstate-<account-id> \
#          --public-access-block-configuration \
#          BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
#        aws dynamodb create-table \
#          --table-name coursellm-tf-lock \
#          --attribute-definitions AttributeName=LockID,AttributeType=S \
#          --key-schema AttributeName=LockID,KeyType=HASH \
#          --billing-mode PAY_PER_REQUEST
#
#   2. Uncomment the block below, replacing the bucket and DynamoDB table names.
#
#   3. `terraform init -migrate-state` and confirm.
#
# Why this matters more here than usual: the RDS master password and the
# application-role password are generated by Terraform and stored in Secrets
# Manager, which means their values exist in Terraform state. State must be a
# remote backend with encryption and versioning, access must be restricted, and
# `*.tfstate` is gitignored. With a local backend the state file sits in this
# directory and must never be committed.
#
# Separate state per environment is the rule: dev and prod are separate root
# modules with separate state keys, never one state file for both.

# terraform {
#   backend "s3" {
#     bucket         = "coursellm-tfstate-REPLACE_WITH_ACCOUNT_ID"
#     key            = "coursellm/dev/terraform.tfstate"
#     region         = "us-east-1"
#     dynamodb_table = "coursellm-tf-lock"
#     encrypt        = true
#   }
# }
